export const industryData = [
  { value: "technology", label: "Technology" },
  { value: "healthcare", label: "Healthcare" },
  { value: "finance", label: "Finance" },
  { value: "education", label: "Education" },
  { value: "construction", label: "Construction" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "retail", label: "Retail" },
  { value: "hospitality", label: "Hospitality" },
  { value: "agriculture", label: "Agriculture" },
  { value: "automotive", label: "Automotive" },
  { value: "real-estate", label: "Real Estate" },
  { value: "transportation", label: "Transportation" },
  { value: "energy", label: "Energy" },
  { value: "entertainment", label: "Entertainment" },
  { value: "marketing", label: "Marketing" },
  { value: "law", label: "Law" },
  { value: "public-sector", label: "Public Sector" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "non-profit", label: "Non-Profit" },
  { value: "pharmaceuticals", label: "Pharmaceuticals" },
  { value: "media", label: "Media" },
  { value: "logistics", label: "Logistics" },
  { value: "mining", label: "Mining" },
  { value: "insurance", label: "Insurance" },
  { value: "food-and-beverage", label: "Food and Beverage" },
  { value: "aerospace", label: "Aerospace" },
  { value: "arts-and-culture", label: "Arts and Culture" },
  { value: "sports", label: "Sports" },
  { value: "ecommerce", label: "E-commerce" },
];
